on: [push]
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - run: go test -v .
      - run: go build -buildmode=c-shared -o lib/build/linux_amd64_geohash_lib_go.so ./geohash_lib.go
      - run: ruby test/geohash_helper_test.rb
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - run: go test
      - run: go build -buildmode=c-shared -o lib/build/darwin_amd64_geohash_lib_go.so ./geohash_lib.go
      - run: ruby test/geohash_helper_test.rb
