on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - run: go test -v .
      - run: go build -buildmode=c-shared -o lib/build/${GOOS}_${GOARCH}_geohash_lib_go.so ./geohash_lib.go
      - run: ruby test/geohash_helper_test.rb
      - name: git setting
        run: |
          git config --local user.email "osd.akira@gmail.com"
          git config --local user.name "osdakira"
      - name: Commit files
        run: |
          git add lib/build/${GOOS}_${GOARCH}_geohash_lib_go.so
          git commit -m "Update so"
          git pull origin ${GITHUB_REF#refs/heads/} --no-rebase
          git push origin ${GITHUB_REF#refs/heads/}
